server:
  port: 8080

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/users/**
        - id: vehicle-service
          uri: lb://Vehicle-Service
          predicates:
            - Path=/vehicles/**
        - id: Parking-Space-Service
          uri: lb://parking-space-service
          predicates:
            - Path=/parking/**
        - id: Payment-Service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
