server:
  port: 8082 # Change per service

spring:
  application:
    name: Parking-Space-Service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
